version: "3.3"
services:
  app:
    build: .
    container_name: RLEPR
    ports:
      - "8050:8050"
    # The first 'false' is for --if_AEtrain, the second 'false' is for --if_RLtrain
    command: ["false", "false"]